spring:
  application:
    name: ghostnetfishing
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: geheim
    url: jdbc:postgresql://localhost:5432/ghostnet

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql